// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://npvyuxwaihvuzgftixqv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5wdnl1eHdhaWh2dXpnZnRpeHF2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI3ODUxMDMsImV4cCI6MjA1ODM2MTEwM30.yQJ1xYl1P0oDh96nzTctq6qo9LNS4qER_qRbnidjjfY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);